* Engine Progress
** Sound
We think that sound, especially in puzzle games is a major contributor to the
overall feel of the game. As mentioned in the other project notebook chapters
(e.g. Physiocal Prototype) one major focus for our development was to capture
the correct feeling of our vision as succinctly as possible so implementing a
sound system was a high priority after the initial engine was work finished
(even thought we forgot to add it to the layers of development in the first
chapter).
*** irrKlang Sound Engine
For the sound eninge in this project we chose to use the irrKlang sound library.
IrrKlang is a object oriented interface designed for games and supports all
current sound formats such as .wav .flac and .mp3. It is able to run on Linux
and Windows which was an important aspect to consider to ensure our cross
platform compability.
*** Additional work
Most of the basic function that irrKlang provides were enough for this game
because our use for now will not exceed simple sound effects and background
music. The only work on top of the irrKlang functions that was needed was the
timing of the effects using the scheduling system of the engine. One additional
interesting fact to note was the possibility to skip the use of a random number
generator for choosing a random sound effect. We thought that this would be
necessary as playing the same sound effect repeatedly for an action such as
sliding is very repetetive. Instead we tried to use a longer sound sample of a
slide and continously loop through it which worked much better than we initially
expected and sounds realistic and varied. A function to chose a random sample
from a group of will still be necessary for the future but the possibility of
implementing the sliding sound effect in such a way is something to take not of
especially due to the fickleness of sound loops in general.
* Alpha Release Content
** Gameplay Features
** Level Structure
** Music & Sound Effects
* Challenges
- jonas
* Outlook
* Meta Info                                                        :noexport:
#+startup: overview
#+options: html-postamble:nil toc:nil title:nil
#+OPTIONS: ^:{}
#+macro: insert_game_name_here qubi
#+macro: insert_team_name_here FünfKopf

#+author: Felix Brendel, Jonas Helms, Van Minh Pham
#+title: Alpha Release: {{{insert_game_name_here}}}

#+latex_header: \input{latex.tex}

